version: "3.8"

services:
  server:
    build: ./
    container_name: cloudstorage
    environment:
      spring.datasource.url: jdbc:postgresql://localhost:8080/postgres
      spring.jpa.hibernate.ddl-auto: create-drop
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
